// File generated by the FlutterFire CLI.
// To regenerate this file, please run: flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD23mIyFu2lT4jEILws6XM-BoQuh6HDaQM',
    appId: '1:14520168544:web:1f93273b1ef6bd435f1305',
    messagingSenderId: '14520168544',
    projectId: 'aquasense-6b25f',
    authDomain: 'aquasense-6b25f.firebaseapp.com',
    databaseURL: 'https://aquasense-6b25f-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-6b25f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23mIyFu2lT4jEILws6XM-BoQuh6HDaQM',
    appId: '1:14520168544:android:2fbcfd648f4cddd75f1305',
    messagingSenderId: '14520168544',
    projectId: 'aquasense-6b25f',
    databaseURL: 'https://aquasense-6b25f-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-6b25f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Get from Firebase Console
    appId: 'YOUR_IOS_APP_ID', // Get from Firebase Console
    messagingSenderId: '14520168544',
    projectId: 'aquasense-6b25f',
    databaseURL: 'https://aquasense-6b25f-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-6b25f.firebasestorage.app',
    iosBundleId: 'aqua.sense1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Get from Firebase Console
    appId: 'YOUR_MACOS_APP_ID', // Get from Firebase Console
    messagingSenderId: '14520168544',
    projectId: 'aquasense-6b25f',
    databaseURL: 'https://aquasense-6b25f-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-6b25f.firebasestorage.app',
    iosBundleId: 'aqua.sense1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY', // Get from Firebase Console
    appId: 'YOUR_WINDOWS_APP_ID', // Get from Firebase Console
    messagingSenderId: '14520168544',
    projectId: 'aquasense-6b25f',
    authDomain: 'aquasense-6b25f.firebaseapp.com',
    databaseURL: 'https://aquasense-6b25f-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-6b25f.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY', // Get from Firebase Console
    appId: 'YOUR_LINUX_APP_ID', // Get from Firebase Console
    messagingSenderId: '14520168544',
    projectId: 'aquasense-6b25f',
    authDomain: 'aquasense-6b25f.firebaseapp.com',
    databaseURL: 'https://aquasense-6b25f-default-rtdb.firebaseio.com',
    storageBucket: 'aquasense-6b25f.firebasestorage.app',
  );
}
